/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kpihx_labs.gestionrisque;

/**
 *
 * @author kpihx
 */
public class GestionRisque extends javax.swing.JFrame {

    /**
     * Creates new form gestionRisqueFrame
     */
    public GestionRisque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salCatLabel = new javax.swing.JLabel();
        ageCatLabel = new javax.swing.JLabel();
        reqCreditLabel = new javax.swing.JLabel();
        salCat = new javax.swing.JComboBox<>(CreditCalculator.getSalaryCategories());
        ageCat = new javax.swing.JComboBox<>(CreditCalculator.getAgeCategories());
        reqCreditInput = new javax.swing.JTextField();
        evalCreditButton = new javax.swing.JButton();
        givenCreditField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionnaire de Risque");

        salCatLabel.setText("Catégorie de salaire (FCFA)");

        ageCatLabel.setText("Catégorie d'âge ");

        reqCreditLabel.setText("Crédit demandé (FCFA)");

        salCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salCatActionPerformed(evt);
            }
        });

        ageCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageCatActionPerformed(evt);
            }
        });

        reqCreditInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        reqCreditInput.setText("1000000");
        reqCreditInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqCreditInputActionPerformed(evt);
            }
        });

        evalCreditButton.setText("Evaluer le Crédit");
        evalCreditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalCreditButtonActionPerformed(evt);
            }
        });

        givenCreditField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Bienvenue M./Mme!");

        jLabel2.setText("Ravi de vous avoir servi!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(givenCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salCatLabel)
                                    .addComponent(ageCatLabel)
                                    .addComponent(reqCreditLabel))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ageCat, javax.swing.GroupLayout.Alignment.LEADING, 0, 277, Short.MAX_VALUE)
                                    .addComponent(salCat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reqCreditInput)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(evalCreditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salCatLabel)
                    .addComponent(salCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageCatLabel)
                    .addComponent(ageCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqCreditLabel)
                    .addComponent(reqCreditInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(evalCreditButton)
                .addGap(28, 28, 28)
                .addComponent(givenCreditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageCatActionPerformed
        ageCategory = (String) ageCat.getSelectedItem();
    }//GEN-LAST:event_ageCatActionPerformed

    private void reqCreditInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqCreditInputActionPerformed
        try {
            reqCredit = Double.valueOf(reqCreditInput.getText());
            if (reqCredit <= 0) { 
                throw new IllegalArgumentException("Le crédit demandé doit être strictement positif!");
            }
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Veuillez entrer un nombre réel valide pour le crédit demandé!");
        }
    }//GEN-LAST:event_reqCreditInputActionPerformed

    private void evalCreditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evalCreditButtonActionPerformed
        ageCatActionPerformed(evt);
        salCatActionPerformed(evt);
        try {
            reqCreditInputActionPerformed(evt);
        } catch (IllegalArgumentException e) {
            givenCreditField.setText(e.getMessage());
            return;
        }
        Client client = new Client(ageCategory, salCategory);
        String evalCredit = CreditCalculator.calculateCredit(client, reqCredit); 
        givenCreditField.setText(evalCredit);
    }//GEN-LAST:event_evalCreditButtonActionPerformed

    private void salCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salCatActionPerformed
        salCategory = (String) salCat.getSelectedItem();
    }//GEN-LAST:event_salCatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRisque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRisque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRisque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRisque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold
        //</editor-fold>
        //</editor-fold
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionRisque().setVisible(true);
            }
        });
    }
    
    private String salCategory, ageCategory;
    private Double reqCredit;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageCat;
    private javax.swing.JLabel ageCatLabel;
    private javax.swing.JButton evalCreditButton;
    private javax.swing.JTextField givenCreditField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField reqCreditInput;
    private javax.swing.JLabel reqCreditLabel;
    private javax.swing.JComboBox<String> salCat;
    private javax.swing.JLabel salCatLabel;
    // End of variables declaration//GEN-END:variables
}
